import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
} from "remotion";

interface TextVideoProps {
  title: string;
  subtitle?: string;
  body?: string;
  backgroundColor?: string;
  titleColor?: string;
  subtitleColor?: string;
  showLogo?: boolean;
}

export const TextVideo: React.FC<TextVideoProps> = ({
  title,
  subtitle,
  body,
  backgroundColor = "#1a1a2e",
  titleColor = "#ffffff",
  subtitleColor = "#a0aec0",
  showLogo = true,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Animations
  const titleOpacity = interpolate(frame, [0, 20], [0, 1], { extrapolateRight: "clamp" });
  const titleScale = spring({ frame, fps, config: { damping: 100, stiffness: 200 } });
  
  const subtitleOpacity = interpolate(frame, [20, 40], [0, 1], { extrapolateRight: "clamp" });
  const subtitleY = interpolate(frame, [20, 40], [20, 0], { extrapolateRight: "clamp" });
  
  const bodyOpacity = interpolate(frame, [40, 60], [0, 1], { extrapolateRight: "clamp" });

  return (
    <AbsoluteFill
      style={{
        background: `linear-gradient(135deg, ${backgroundColor} 0%, #16213e 100%)`,
        fontFamily: "system-ui, -apple-system, sans-serif",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: 60,
      }}
    >
      {/* Logo */}
      {showLogo && (
        <div
          style={{
            position: "absolute",
            top: 40,
            left: 60,
            opacity: titleOpacity,
            transform: `scale(${titleScale})`,
            display: "flex",
            alignItems: "center",
          }}
        >
          <span style={{ fontSize: 48 }}>🦞</span>
          <span style={{ fontSize: 32, fontWeight: "bold", color: "#fff", marginLeft: 16 }}>
            Kingdom Claw
          </span>
        </div>
      )}

      {/* Title */}
      <div
        style={{
          fontSize: 80,
          fontWeight: "bold",
          color: titleColor,
          opacity: titleOpacity,
          transform: `scale(${titleScale})`,
          textAlign: "center",
          maxWidth: "80%",
        }}
      >
        {title}
      </div>

      {/* Subtitle */}
      {subtitle && (
        <div
          style={{
            fontSize: 48,
            color: subtitleColor,
            marginTop: 30,
            opacity: subtitleOpacity,
            transform: `translateY(${subtitleY}px)`,
            textAlign: "center",
            maxWidth: "80%",
          }}
        >
          {subtitle}
        </div>
      )}

      {/* Body */}
      {body && (
        <div
          style={{
            fontSize: 32,
            color: "#e2e8f0",
            marginTop: 40,
            opacity: bodyOpacity,
            textAlign: "center",
            maxWidth: "70%",
            lineHeight: 1.6,
          }}
        >
          {body}
        </div>
      )}

      {/* Footer */}
      <div
        style={{
          position: "absolute",
          bottom: 40,
          fontSize: 24,
          color: "#718096",
          opacity: interpolate(frame, [60, 80], [0, 1], { extrapolateRight: "clamp" }),
        }}
      >
        Generated by Kingdom Claw
      </div>
    </AbsoluteFill>
  );
};
